name: user_preferences
description: This is a port of Android SharedPreferences, providing, a persistent store for simple data. Data is persisted to disk asynchronously.
version: 0.1.1+4
author: long1eu <home@long1.eu>
homepage: https://github.com/long1eu/user_preferences

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  path: ^1.6.2

dev_dependencies:
  test: ^1.5.1
